Auslagern hardcodierter texte
bettercodepaul/swt2-bsa-frontend pull request #8
Opened 2022-03-29 09:04 UTC by NicoGoe

Von - zu _ geändert.

2022-03-29 10:01 UTC, DennisBaerXY requested changes
Bitte die Bennung in CAPS wie in der Review davor gesagt

2022-03-29 10:01 UTC, DennisBaerXY commented on bogenliga/src/assets/i18n/de.json
> +        "Einzel_als_PDF": {
Bitte in Caps die Benennung wie im Review davor angesprochen.

2022-03-30 08:04 UTC, DennisBaerXY requested changes
Wettkampftageins ist in en.json immernoch klein

2022-03-30 08:47 UTC, DennisBaerXY requested changes
Eine Sache ist immernoch nicht groß. Schau bitte den Committee nochmal an bevor du commitest.

2022-03-30 08:55 UTC, NicoGoe commented
Hab jetzt alles nochmal durchgeschaut hatte was in de und en vergessen, hab nur ein Teil davon Groß geschrieben. @DennisBaerXY Sorry, für den aufwand.

2022-03-30 08:56 UTC, DennisBaerXY approved these changes
Okay passt jetzt. 
Danke 🚀🚀🚀🚀🚀🚀🚀🚀

2022-03-30 08:56 UTC, merged